[package]
name = "tai"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.4.1"
clap = { version = "4.5.54", features = ["derive"] }
dirs-next = "2"
encoding_rs = "0.8"
rig-core = "0.28.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
