[package]
name = "tai-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indicatif = "0.17"
ratatui = "0.29"
crossterm = "0.28"
termimad = "0.31"
tracing = "0.1"
unicode-width = "0.2.0"
